Nim for Discox
v1rbox/discox pull request #188
Opened 2023-10-31 10:24 UTC by xTrayambak

**What kind of change does this PR introduce?**  
This PR allows you to write commands for Discox within the [Nim](https://nim-lang.org) programming language using the dimscord library.

**Describe the changes proposed in the pull request** 
The Python code is now run by an `init` binary written in Nim, meaning everything written in Python still works just as it would.

**Does this PR introduce a breaking change?** 
Nothing. The makefiles and Nix flake have been modified to work with the new system from now on.
Note that `nim` and `nimble` are now a required dependency to run discox.

**Does this PR introduce changes to the database?**
No.

**Other information:** 
Nim is very based.

please accept this, I spent 3 hours of my life doing this
kthxbye :3

2023-10-31 13:29 UTC, timelessnesses commented
jesus christ

2023-10-31 13:51 UTC, timelessnesses requested changes
doesn't looked very cross-platform, do we have something like python bindings instead of spawning 2 instances of bot?, still no support for mysql bridge

2023-10-31 13:51 UTC, timelessnesses commented on bot/bridge/bot.nim
> +  discard tp.spawn execCmd("python3 bot")
is this just simply spawn 2 instances of the bot?

2023-10-31 13:51 UTC, timelessnesses commented on bot/commands/minecraft/status.nim
> +          )
this is not identical to the python version

2023-10-31 13:51 UTC, timelessnesses commented on discox.nimble
> +requires "mcsrvstat.nim"
is this only support windows?

2023-10-31 14:07 UTC, xTrayambak commented on bot/bridge/bot.nim
> +  discard tp.spawn execCmd("python3 bot")
Yeah. It doesn't seem to cause any trouble. It would be a massive pain to bind everything and it would slow things down. This ensures nothing slows down. I'll eventually add MySQL stuff.

2023-10-31 14:07 UTC, xTrayambak commented
> jesus christ

:troll:

2023-10-31 14:08 UTC, xTrayambak commented on bot/commands/minecraft/status.nim
> +          )
There's a few extra fields, but other than that it looks the same. I'll fix the embed color.

2023-10-31 20:34 UTC, jtbx commented
No.

2023-10-31 23:40 UTC, xTrayambak commented
Why not? Doesn't hurt anyone, plus I'll be able to contribute to more commands since I've basically forgotten Python.

2023-10-31 23:45 UTC, jtbx commented
I think this is a bad idea because you've redesigned the core bot "infrastructure" to use Nim primarily; no one will be able to maintain it except you.

2023-10-31 23:47 UTC, xTrayambak commented
It's very easy to change it, even now. It seems you haven't seen the source code and are assuming things.

2023-10-31 23:53 UTC, jtbx commented
I *have* seen your changes but I just think it reduces maintainability moving the entire thing to Nim. Nobody even knows how to use Nim's tooling except you, nor does anyone here use the Nim language, so why is this even needed?

The Python interpreter is a common program found on most systems but Nim is not, further increasing the need for unnecessary dependencies.

2023-10-31 23:55 UTC, xTrayambak commented
Nim's tooling is something a literal child can use. Plus, you don't even need to. I've fixed the Makefile and Nix Flake to work properly, so in the best case, you won't have to. I'll take care of any issues that occur, though there should be none.

2023-10-31 23:55 UTC, xTrayambak commented
Nim is available in a lot of software repos nowadays, with the major exception being Fedora Linux.

2023-11-01 02:30 UTC, timelessnesses commented
i think this can be improved to something like
a program that is built to an executable kinda like<br>
you have 2 commands one for listing commands with its description and one for calling the command. then there's wrapper for each programming language that communicate through stdin and stdout in something like json format. then it could in theory support every other languages

2023-11-01 02:31 UTC, timelessnesses commented
so now mysql bridging isn't the problem because python side would query it then send it back through stdin

2023-11-01 10:59 UTC, timelessnesses commented
let me come up with a binding rq

2023-11-01 16:45 UTC, xTrayambak commented
> i think this can be improved to something like
> a program that is built to an executable kinda like<br>
> you have 2 commands one for listing commands with its description and one for calling the command. then there's wrapper for each programming language that communicate through stdin and stdout in something like json format. then it could in theory support every other languages
> 

This seems like a good idea. I'll try to implement this.

2023-11-01 18:45 UTC, jtbx commented on flake.nix
> +		       nimble buildBinary
```suggestion
		           nimble buildBinary
```

2024-01-24 04:56 UTC, jtbx commented
What's the current status on this?

2024-01-24 14:48 UTC, xTrayambak commented
Turns out, I never got around to working on that

2024-01-28 07:04 UTC, closed without merging